// Code generated by MockGen. DO NOT EDIT.
// Source: reminder_repository.go
//
// Generated by this command:
//
//	mockgen -source=reminder_repository.go -destination=./mocks/reminder_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/Helltale/take-your-pills-on-time/internal/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReminderRepository is a mock of ReminderRepository interface.
type MockReminderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReminderRepositoryMockRecorder
	isgomock struct{}
}

// MockReminderRepositoryMockRecorder is the mock recorder for MockReminderRepository.
type MockReminderRepositoryMockRecorder struct {
	mock *MockReminderRepository
}

// NewMockReminderRepository creates a new mock instance.
func NewMockReminderRepository(ctrl *gomock.Controller) *MockReminderRepository {
	mock := &MockReminderRepository{ctrl: ctrl}
	mock.recorder = &MockReminderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderRepository) EXPECT() *MockReminderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReminderRepository) Create(ctx context.Context, reminder *entities.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReminderRepositoryMockRecorder) Create(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReminderRepository)(nil).Create), ctx, reminder)
}

// Delete mocks base method.
func (m *MockReminderRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReminderRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReminderRepository)(nil).Delete), ctx, id)
}

// GetActiveByUserID mocks base method.
func (m *MockReminderRepository) GetActiveByUserID(ctx context.Context, userID uuid.UUID) ([]*entities.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entities.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByUserID indicates an expected call of GetActiveByUserID.
func (mr *MockReminderRepositoryMockRecorder) GetActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByUserID", reflect.TypeOf((*MockReminderRepository)(nil).GetActiveByUserID), ctx, userID)
}

// GetByID mocks base method.
func (m *MockReminderRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReminderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReminderRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockReminderRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*entities.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entities.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockReminderRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockReminderRepository)(nil).GetByUserID), ctx, userID)
}

// GetDueReminders mocks base method.
func (m *MockReminderRepository) GetDueReminders(ctx context.Context) ([]*entities.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDueReminders", ctx)
	ret0, _ := ret[0].([]*entities.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDueReminders indicates an expected call of GetDueReminders.
func (mr *MockReminderRepositoryMockRecorder) GetDueReminders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDueReminders", reflect.TypeOf((*MockReminderRepository)(nil).GetDueReminders), ctx)
}

// Update mocks base method.
func (m *MockReminderRepository) Update(ctx context.Context, reminder *entities.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReminderRepositoryMockRecorder) Update(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReminderRepository)(nil).Update), ctx, reminder)
}

// UpdateLastSentAt mocks base method.
func (m *MockReminderRepository) UpdateLastSentAt(ctx context.Context, id uuid.UUID, lastSentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSentAt", ctx, id, lastSentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSentAt indicates an expected call of UpdateLastSentAt.
func (mr *MockReminderRepositoryMockRecorder) UpdateLastSentAt(ctx, id, lastSentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSentAt", reflect.TypeOf((*MockReminderRepository)(nil).UpdateLastSentAt), ctx, id, lastSentAt)
}

// UpdateNextSendAt mocks base method.
func (m *MockReminderRepository) UpdateNextSendAt(ctx context.Context, id uuid.UUID, nextSendAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNextSendAt", ctx, id, nextSendAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNextSendAt indicates an expected call of UpdateNextSendAt.
func (mr *MockReminderRepositoryMockRecorder) UpdateNextSendAt(ctx, id, nextSendAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNextSendAt", reflect.TypeOf((*MockReminderRepository)(nil).UpdateNextSendAt), ctx, id, nextSendAt)
}
