// Code generated by MockGen. DO NOT EDIT.
// Source: reminder_execution_repository.go
//
// Generated by this command:
//
//	mockgen -source=reminder_execution_repository.go -destination=./mocks/reminder_execution_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/Helltale/take-your-pills-on-time/internal/entities"
	repository "github.com/Helltale/take-your-pills-on-time/internal/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReminderExecutionRepository is a mock of ReminderExecutionRepository interface.
type MockReminderExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReminderExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockReminderExecutionRepositoryMockRecorder is the mock recorder for MockReminderExecutionRepository.
type MockReminderExecutionRepositoryMockRecorder struct {
	mock *MockReminderExecutionRepository
}

// NewMockReminderExecutionRepository creates a new mock instance.
func NewMockReminderExecutionRepository(ctrl *gomock.Controller) *MockReminderExecutionRepository {
	mock := &MockReminderExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockReminderExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderExecutionRepository) EXPECT() *MockReminderExecutionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReminderExecutionRepository) Create(ctx context.Context, execution *entities.ReminderExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReminderExecutionRepositoryMockRecorder) Create(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReminderExecutionRepository)(nil).Create), ctx, execution)
}

// GetByReminderID mocks base method.
func (m *MockReminderExecutionRepository) GetByReminderID(ctx context.Context, reminderID uuid.UUID, limit int) ([]*entities.ReminderExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReminderID", ctx, reminderID, limit)
	ret0, _ := ret[0].([]*entities.ReminderExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReminderID indicates an expected call of GetByReminderID.
func (mr *MockReminderExecutionRepositoryMockRecorder) GetByReminderID(ctx, reminderID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReminderID", reflect.TypeOf((*MockReminderExecutionRepository)(nil).GetByReminderID), ctx, reminderID, limit)
}

// GetByUserID mocks base method.
func (m *MockReminderExecutionRepository) GetByUserID(ctx context.Context, userID uuid.UUID, limit int) ([]*entities.ReminderExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, limit)
	ret0, _ := ret[0].([]*entities.ReminderExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockReminderExecutionRepositoryMockRecorder) GetByUserID(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockReminderExecutionRepository)(nil).GetByUserID), ctx, userID, limit)
}

// GetStatisticsByReminderID mocks base method.
func (m *MockReminderExecutionRepository) GetStatisticsByReminderID(ctx context.Context, reminderID uuid.UUID, fromDate, toDate time.Time) (*repository.ExecutionStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsByReminderID", ctx, reminderID, fromDate, toDate)
	ret0, _ := ret[0].(*repository.ExecutionStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsByReminderID indicates an expected call of GetStatisticsByReminderID.
func (mr *MockReminderExecutionRepositoryMockRecorder) GetStatisticsByReminderID(ctx, reminderID, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsByReminderID", reflect.TypeOf((*MockReminderExecutionRepository)(nil).GetStatisticsByReminderID), ctx, reminderID, fromDate, toDate)
}

// GetStatisticsByUserID mocks base method.
func (m *MockReminderExecutionRepository) GetStatisticsByUserID(ctx context.Context, userID uuid.UUID, fromDate, toDate time.Time) (*repository.ExecutionStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsByUserID", ctx, userID, fromDate, toDate)
	ret0, _ := ret[0].(*repository.ExecutionStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsByUserID indicates an expected call of GetStatisticsByUserID.
func (mr *MockReminderExecutionRepositoryMockRecorder) GetStatisticsByUserID(ctx, userID, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsByUserID", reflect.TypeOf((*MockReminderExecutionRepository)(nil).GetStatisticsByUserID), ctx, userID, fromDate, toDate)
}

// UpdateStatus mocks base method.
func (m *MockReminderExecutionRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status entities.ExecutionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockReminderExecutionRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockReminderExecutionRepository)(nil).UpdateStatus), ctx, id, status)
}
